### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [harlanhong/CVPR2022-DaGAN#10]
Hi, would you be interested in adding DaGAN to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community.  Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by harlanhong** [comment]
That's awesome, thanks, I will Integrate DaGAN into Huggingface Spaces in near future.

**Comment by harlanhong** [comment]
Hi @AK391 ,

The Hugging Face is a great platform for us to present our project. However, I have met a problem when I deployed my code on it, It seems quite simple for you experienced guys with that platform:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/19970321/164979155-c19966c2-66e1-4cfb-9aea-e193023cda74.png">

**Comment by AK391** [comment]
@harlanhong Hi, it looks like the requirements.txt file is missing so similar to github you can add a requirements.txt file to spaces https://github.com/harlanhong/CVPR2022-DaGAN/blob/master/requirements.txt

**Comment by harlanhong** [comment]
> @harlanhong Hi, it looks like the requirements.txt file is missing so similar to github you can add a requirements.txt file to spaces https://github.com/harlanhong/CVPR2022-DaGAN/blob/master/requirements.txt

Thanks, it works. I will share the space link with you soon.

**Comment by harlanhong** [comment]
How to use GPU in spaces. I can now run my code on it but it cost too much time when using the CPU.
When I load my model on GPU, an error will occur:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/19970321/165046624-64388969-1723-493d-8b6b-b6c77359c269.png">

**Comment by AK391** [comment]
@harlanhong Hi, from the spaces docs: https://huggingface.co/docs/hub/spaces

Each Spaces environment is limited to 16GB RAM and 8 CPU cores. Organization [subscribers](https://huggingface.co/pricing) (Lab, Startup, and Enterprise) can access Spaces with one T4 GPU on a case-by-case basis. Please email us at website at huggingface.co or let us know on [Twitter](https://twitter.com/huggingface) if you need one.

I can also send a request to assign a gpu for this space

**Comment by harlanhong** [comment]
> @harlanhong Hi, from the spaces docs: https://huggingface.co/docs/hub/spaces
> 
> Each Spaces environment is limited to 16GB RAM and 8 CPU cores. Organization [subscribers](https://huggingface.co/pricing) (Lab, Startup, and Enterprise) can access Spaces with one T4 GPU on a case-by-case basis. Please email us at website at huggingface.co or let us know on [Twitter](https://twitter.com/huggingface) if you need one.
> 
> I can also send a request to assign a gpu for this space

Many thanks.

**Comment by osanseviero** [comment]
Hey there! :wave: We opened an internal PR to provide a temporal GPU, we'll let you know once it's deployed.

**Comment by AK391** [comment]
thanks @osanseviero also @harlanhong huggingface can also most models for free, so the pretrained checkpoints in one drive for example can be added to the huggingface model hub under your username or a organization name, more details here:  https://huggingface.co/docs/hub/adding-a-model

**Comment by AK391** [comment]
thanks @osanseviero, was testing out the space, still seem to be taking some time, 200 seconds so far with one of the examples and the output is not showing @harlanhong

**Comment by harlanhong** [comment]
> The demo is currently running `demo_dagan` script every inference call, which means the model is reloaded every time and this is what might be making things slow.

Oh, I see. Thanks for your reminder.

**Comment by harlanhong** [comment]
> thanks @osanseviero, was testing out the space, still seem to be taking some time, 200 seconds so far with one of the examples and the output is not showing @harlanhong

Hi @AK391, I have modified my code to load everything before launching, but when I test it I get an error, however, the log file doesn't report anything about that error.

**Comment by harlanhong** [comment]
> thanks @osanseviero, was testing out the space, still seem to be taking some time, 200 seconds so far with one of the examples and the output is not showing @harlanhong

Hi @AK391, I have modified my code to load everything before launching, but when I test it I get an error, however, the log file doesn't report anything about that error.

**Comment by AK391** [comment]
@harlanhong sorry for the late response, are you still getting this error and how long is inference taking on the gpu space?

**Comment by AK391** [comment]
@harlanhong currently its running over 600 seconds
<img width="1267" alt="Screen Shot 2022-04-30 at 1 37 45 AM" src="https://user-images.githubusercontent.com/81195143/166092975-3ed3a30c-ae40-4cf9-b19b-d2ebc9edb82d.png">

**Comment by Sreerag-ibtl** [comment]
If you have the Gradio app ready it'll be easy to have a notebook and run it from Colab since GPU is readily available. By the way, is there a branch I can check out?

**Comment by NimaBoscarino** [comment]
Hi @harlanhong! Would you be interested in making the checkpoint on the Hub as a model repo? It would make it easy for our community to find your model and you could attach some tags and documentation to it, like this model: https://huggingface.co/bert-base-uncased

[There's documentation on how to do this](https://huggingface.co/docs/hub/models-uploading), but I'm also happy to take it on or help out!
