### ISSUE TITLE
Question regarding output of  DepthAwareAttention

### ISSUE THREAD

**Issue by mdv3101** [harlanhong/CVPR2022-DaGAN#14]
In the DepthAwareAttention module, the inputs are: depth_image and output feature map generated by occlusion map [line 195](https://github.com/harlanhong/CVPR2022-DaGAN/blob/d0a169333e34c41b80e714197c30090d3836698e/modules/generator.py#L195).

depth_image is stored in 'source' while output feature is stored in 'feat'.

There is one variable gamma [line 66](https://github.com/harlanhong/CVPR2022-DaGAN/blob/master/modules/generator.py#L66), which is basically a zero tensor.  `self.gamma = nn.Parameter(torch.zeros(1))`

After doing all the operations in forward pass, you are getting an output feature map. It is then multiplied with gamma and feat is added [line 87](https://github.com/harlanhong/CVPR2022-DaGAN/blob/master/modules/generator.py#L87).
`out = self.gamma*out + feat`

That means all the operations performed during the forward pass are multiplied to zero and the original output features were returned. That makes the entire DepthAwareAttention useless, as the attention returned was also never used in the code.

Can you please clarify on this?

**Comment by harlanhong** [comment]
Hi @mdv3101 ,

The "self.gamma" is a trainable parameter that serves as the input gate for the attention result. It similars to [Highway networks](https://arxiv.org/abs/1505.00387). Our network can learn a proper value for gamma after training to control the input of the attention result.

**Comment by mdv3101** [comment]
Hi @harlanhong ,
Thanks for clarifying.
