### ISSUE TITLE
Size of input

### ISSUE THREAD

**Issue by NikitaKononov** [harlanhong/CVPR2022-DaGAN#15]
Hello
Thanks for your great work!
I have a question, does your model support input resolution higher, than 256px? 512px for example
I see that in code input video and image are resized to 256px, so causes the loss of visual quality 
Is there a way to use 512x512 img/vid without losing quality?

**Comment by harlanhong** [comment]
Hi @NikitaKononov,

We only use 256x images for the amount of computation. If you want to use larger images, you can consider adding several downsampling convolutional layers at the beginning of the network.

**Comment by NikitaKononov** [comment]
@harlanhong Thanks!
So I should retrain model with additional layers? Or adding downsampling layers doesn't require model retraining? I am sorry, if my question is silly :)

**Comment by harlanhong** [comment]
If you add additional layers, you should retrain the whole network.
