### ISSUE TITLE
Suggestion: Add automatic face cropping in demo.py

### ISSUE THREAD

**Issue by Vadim2S** [harlanhong/CVPR2022-DaGAN#21]
Output result significally related to input image. There few samples:

1) Photo as is
2) Photo with manual crop
3) Photo converted to video and cropped with crop-video.py

Please, crop input image inside demo.py automatically

https://user-images.githubusercontent.com/84853762/169252080-db016d04-2f9c-4bb3-9d84-d5de0450d2a6.mp4

https://user-images.githubusercontent.com/84853762/169252087-5a8c9a5a-0eeb-436f-874f-0745683e64b3.mp4

https://user-images.githubusercontent.com/84853762/169252089-a8b37f66-897b-4092-a109-86295fecbf15.mp4

**Comment by harlanhong** [comment]
Thanks for your suggestion, will do it soon!

**Comment by Vadim2S** [comment]
Well... This issue marked as "completed". But... May be I am missing something but I am can not see any code changes related for this issue. Where is it? File/Line?

**Comment by Thisisaname1125** [comment]
> Well... This issue marked as "completed". But... May be I am missing something but I am can not see any code changes related for this issue. Where is it? File/Line?

maybe you can reference the "crop-video.py".
