### ISSUE TITLE
Fix some codes about py-feat library

### ISSUE THREAD

**Issue by samsara-ku** [harlanhong/CVPR2022-DaGAN#25]
Hi @harlanhong !

First, I'm very pleased to see your works, DaGAN. Thanks for your effort.
The reason why I issue this post is I just want to fix your code a little bit.
In your `utils.py`, there are some codes using `py-feat` library and this a causes of problem.
I don't know which version of `py-feat` you use, but no matter what you should change some codes like this way due to latest version using this way:

```
p1 = out1.facepose().values # AS-IS
p1 = out1.facepose.values # TO-BE
```

because latest version of py-feat uses facepose as property like this:
```
@property
    def facepose(self):
        """Returns the facepose data using the columns set in fex.facepose_columns

        Returns:
            DataFrame: facepose data
        """
        return self[self.facepose_columns]
```

Could you fix this problems for anybody who will use this codes?

**Comment by harlanhong** [comment]
Hi @samsara-ku 

Thanks for your suggestion. I have merged the modification.

**Comment by samsara-ku** [comment]
Hi, @harlanhong 

I'm sorry for bother you, but could you please change this codes?

```
# AS-IS
gt_aus = out_gt.aus().values
generate_aus = out_generat.aus().values
# TO-BE
gt_aus = out_gt.aus.values
generate_aus = out_generat.aus.values
```

Because of poor English skills, I couldn't convey my intentions accurately.

**Comment by harlanhong** [comment]
> Hi, @harlanhong
> 
> I'm sorry for bothering you, but could you please change this codes?
> 
> ```
> # AS-IS
> gt_aus = out_gt.aus().values
> generate_aus = out_generat.aus().values
> # TO-BE
> gt_aus = out_gt.aus.values
> generate_aus = out_generat.aus.values
> ```
> 
> Because of poor English skills, I couldn't convey my intentions accurately.

Done! Thanks.
