### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by Ha0Tang** [harlanhong/CVPR2022-DaGAN#26]
Processing /data/fhongac/workspace/src/CVPR22_DaGAN/torch-1.9.0+cu111-cp37-cp37m-linux_x86_64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/data/fhongac/workspace/src/CVPR22_DaGAN/torch-1.9.0+cu111-cp37-cp37m-linux_x86_64.whl'

**Comment by harlanhong** [comment]
Please download the torch-1.9.0+cu111-cp37-cp37m-linux_x86_64.whl and install it manually.
