### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by Ha0Tang** [harlanhong/CVPR2022-DaGAN#27]
when i run this command `CUDA_VISIBLE_DEVICES=0 python demo.py  --config config/vox-adv-256.yaml --driving_video ./example_video.mp4 --source_image ./example_image.png --checkpoint ./checkpoints/SPADE_DaGAN_vox_adv_256.pth.tar --relative --adapt_scale --kp_num 15 --generator SPADEDepthAwareGenerator --result_video results/example_out.mp4 --find_best_frame`

I got the following error：
Traceback (most recent call last):
  File "demo.py", line 169, in <module>
    depth_encoder.load_state_dict(filtered_dict_enc)
  File "/home/miniconda3/envs/dagan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetEncoder:
	size mismatch for encoder.layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for encoder.layer1.1.conv1.weight: copying a param with shape torch.Size([64, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for encoder.layer2.0.conv1.weight: copying a param with shape torch.Size([128, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
	size mismatch for encoder.layer2.0.downsample.0.weight: copying a param with shape torch.Size([512, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 64, 1, 1]).
	size mismatch for encoder.layer2.0.downsample.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encoder.layer2.0.downsample.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encoder.layer2.0.downsample.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encoder.layer2.0.downsample.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encoder.layer2.1.conv1.weight: copying a param with shape torch.Size([128, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for encoder.layer3.0.conv1.weight: copying a param with shape torch.Size([256, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
	size mismatch for encoder.layer3.0.downsample.0.weight: copying a param with shape torch.Size([1024, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).
	size mismatch for encoder.layer3.0.downsample.1.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.layer3.0.downsample.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.layer3.0.downsample.1.running_mean: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.layer3.0.downsample.1.running_var: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.layer3.1.conv1.weight: copying a param with shape torch.Size([256, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for encoder.layer4.0.conv1.weight: copying a param with shape torch.Size([512, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 256, 3, 3]).
	size mismatch for encoder.layer4.0.downsample.0.weight: copying a param with shape torch.Size([2048, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 256, 1, 1]).
	size mismatch for encoder.layer4.0.downsample.1.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layer4.0.downsample.1.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layer4.0.downsample.1.running_mean: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layer4.0.downsample.1.running_var: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.layer4.1.conv1.weight: copying a param with shape torch.Size([512, 2048, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for encoder.fc.weight: copying a param with shape torch.Size([1000, 2048]) from checkpoint, the shape in current model is torch.Size([1000, 512]).

**Comment by harlanhong** [comment]
Sorry, My mistake. If you are using the depth model of depth_face_model_Voxceleb2_10w, you can set this line https://github.com/harlanhong/CVPR2022-DaGAN/blob/c594a2eb43d9f74fac4f783de26aa7ee3e5cbe35/demo.py#L164 to 50 layers, that is :
`depth_encoder = depth.ResnetEncoder(50, False)`

**Comment by muxiddin19** [comment]
> Sorry, my mistake. If you are using the depth model of depth_face_model_Voxceleb2_10w, you can set this line
> 
> https://github.com/harlanhong/CVPR2022-DaGAN/blob/c594a2eb43d9f74fac4f783de26aa7ee3e5cbe35/demo.py#L164
> 
> to 50 layers, that is :
> `depth_encoder = depth.ResnetEncoder(50, False)`

Thanks for your great job! When I ran both DepAwareGenerator and DepAwareGenerator with 18 layers, it was run without error. However, when running SpadeDepAwareGenerator with 50 layers, there was an error. I am uploading some captures from the screen. Please can you give some tips for the solution?
![image](https://user-images.githubusercontent.com/54941476/179447993-1018c8b9-7869-4dac-b775-c5f68ef505ac.png)
![image](https://user-images.githubusercontent.com/54941476/179448015-2f9239d0-47be-4a37-90a6-a11514e65557.png)
![image](https://user-images.githubusercontent.com/54941476/179448052-5c567ab3-b9e4-486f-bcd1-9b5bebc77a7a.png)

**Comment by harlanhong** [comment]
My mistake. Let me make it more clear.

There are two types of depth checkpoints in the onedrive:
![image](https://user-images.githubusercontent.com/19970321/179522269-775d6954-022a-47e0-a228-44f653ecfde2.png)

if you use the first one, you should rewrite the code as:
`depth_encoder = depth.ResnetEncoder(18, False) `

while you use the second one, depth_face_model_Voxceleb2_10w, you should use 50 layers architecture:
`depth_encoder = depth.ResnetEncoder(50, False) `

Thanks.
