### ISSUE TITLE
Error in running a demo version!

### ISSUE THREAD

**Issue by muxiddin19** [harlanhong/CVPR2022-DaGAN#32]
Hello! Thanks for sharing openly amazing work! My research is also related to generating talking faces. I face error when tried to run: 
CUDA_VISIBLE_DEVICES=0 python demo.py  --config config/vox-adv-256.yaml --driving_video data/2.mp4 --source_image data/2.jpg --checkpoint depth/models/weights_19/encoder.pth --relative --adapt_scale --kp_num 15 --generator DepthAwareGenerator
![image](https://user-images.githubusercontent.com/54941476/179431521-8f5de97e-5920-4414-bad6-8a04a717082a.png)
Can you please correct me where I made mistakes while running the demo one?

**Comment by harlanhong** [comment]
Could you please crop the whole message of your error? I can only find that the error occurs when loading the checkpoints.

**Comment by muxiddin19** [comment]
Thanks for your reply! Actually, it was the full message. 
When I made some changes like:
CUDA_VISIBLE_DEVICES=0 python demo.py  --config config/vox-adv-256.yaml --driving_video data/2.mp4 --source_image data/2.jpg --checkpoint checkpoints/DaGAN_vox_adv_256.pth.tar --relative --adapt_scale --kp_num 15 --generator DepthAwareGenerator --result_video results/example_out.mp4 --find_best_frame
It worked without any error. Here are the some screenshots:

**Comment by harlanhong** [comment]
Oh, I see. You just mistook the checkpoint of the depth network for the Dagan.
