### ISSUE TITLE
About measurement question

### ISSUE THREAD

**Issue by samsara-ku** [harlanhong/CVPR2022-DaGAN#37]
Hi, @harlanhong . First, I appreciate your nice work in this fields.

I'm just asking you how to measure the details of your metric result.

Did you write simple codes or just import library functions to measure those results in tables?

And if you wrote the codes, could you share that? If not, what library did you import to measure those results?

Thank you.

![image](https://user-images.githubusercontent.com/59246456/188566622-5e31d0c0-7a3a-4773-a3bd-2d4796828fee.png)

**Comment by harlanhong** [comment]
Hi, sorry for the delay. I am working on ICLR, and I will upload the evaluation code after finishing my work.

**Comment by samsara-ku** [comment]
@harlanhong 

Thanks for your replying.
