### ISSUE TITLE
Is the audio supported in the generated video? 

### ISSUE THREAD

**Issue by tikitong** [harlanhong/CVPR2022-DaGAN#39]
Is there a way to keep the audio in the generated video? Many thanks.

**Comment by harlanhong** [comment]
will go back to you after 8pm, you know, ICLR :)

**Comment by harlanhong** [comment]
Sure, you can use a tool to divide a diving video into audio and video frames, then merge the audio and generated video frames. I think there are many tools can achieve this goal.
