### ISSUE TITLE
Error No such file or directory: 'depth/models/weights_19/encoder.pth'

### ISSUE THREAD

**Issue by tikitong** [harlanhong/CVPR2022-DaGAN#40]
I downloaded the pre-trained weights from the onedrive `DaGAN_vox_adv_256.pth.tar` and put it in a _checkpoints_ directory.
When I run the demo command with --cpu I get the following error:
```
(dagan) user@Users-MacBook-Air CVPR2022-DaGAN % python demo.py --config config/vox-adv-256.yaml --driving_video ./assets/driving.mp4 --source_image ./assets/leo.jpg --checkpoint ./checkpoints/DaGAN_vox_adv_256.pth.tar --relative --adapt_scale --kp_num 15 --generator DepthAwareGenerator --cpu                 
Traceback (most recent call last):
  File "demo.py", line 165, in <module>
    loaded_dict_enc = torch.load('depth/models/weights_19/encoder.pth')
  File "/Users/user/miniconda3/envs/dagan/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/user/miniconda3/envs/dagan/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/user/miniconda3/envs/dagan/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'depth/models/weights_19/encoder.pth'
```
How can I solve it? Many thanks, great job and good luck for ICLR :) !

**Comment by harlanhong** [comment]
The path is wrong, you could figure it out by yourself. Just put the .pth file in the right path.

**Comment by tikitong** [comment]
Yes I have changed the path, thanks. Just to know, where does the base path `depth/models/weights_19/encoder.pth` come from? Did you use the same weight files as the ones provided in the one drive for the demo?

**Comment by balumuriraj** [comment]
I am also having the same error. How to fix this issue?

**Comment by tikitong** [comment]
@balumuriraj you need to download the [pre-trained checkpoints](https://github.com/harlanhong/CVPR2022-DaGAN#pre-trained-checkpoint) from the readme. And in the _demo.py_ file:

Replace 
`loaded_dict_enc = torch.load('depth/models/weights_19/encoder.pth')` by `loaded_dict_enc = torch.load('checkpoints/depth_face_model/encoder.pth')`

`loaded_dict_dec = torch.load('depth/models/weights_19/depth.pth')` with `loaded_dict_enc = torch.load('checkpoints/depth_face_model/depth.pth')`

**Comment by balumuriraj** [comment]
Thanks @tikitong . It is working now.
