### ISSUE TITLE
crop face

### ISSUE THREAD

**Issue by Carlyx** [harlanhong/CVPR2022-DaGAN#48]
Your work is amazing!

But I have two questions：
1. Is it possible to pad more borders when cropping faces? Or does it have to crop the face strictly according to the detected box?
2. https://github.com/harlanhong/CVPR2022-DaGAN/blob/78b22edcdbb4192b81c5adf343f980b42cddfe5d/crop-video.py#L25 
    When -1 is used, the IndexError is reported.

**Comment by harlanhong** [comment]
1/ You don't have to crop the face strictly. You can just make the source and driving similar. For example, they contain the same proportion of body parts in the image.

2/ The length of "bboxes" is 0. You should check that.

**Comment by Carlyx** [comment]
1/ Got it~

2/ The IndexError is about https://github.com/harlanhong/CVPR2022-DaGAN/blob/78b22edcdbb4192b81c5adf343f980b42cddfe5d/crop-video.py#L33
![微信截图_20221029103443](https://user-images.githubusercontent.com/34021717/198780973-4603bc08-15c5-4254-84a1-2418cad1e5e5.png)

With -1, boxA is [ 62  45 211]  and  boxB is [ 62  45 211].
W/o -1, boxA is [ 62  45 211 194] and boxB is[ 62  45 211 194].

**Comment by harlanhong** [comment]
Could you upload the video here? Or you can debug it step by step.  You can also try again with an another video.

**Comment by Carlyx** [comment]
> Could you upload the video here? Or you can debug it step by step. You can also try again with an another video.

I tried three different videos, and got the same error.

https://user-images.githubusercontent.com/34021717/198818099-ac9e138f-a0e8-4893-b803-4686a7f865e6.mp4


https://user-images.githubusercontent.com/34021717/198818102-04fe5344-1a87-414e-8490-517e6685b014.mp4


https://user-images.githubusercontent.com/34021717/198818104-3cef54d9-3c1c-4a8e-877a-c323b964f367.mp4

**Comment by harlanhong** [comment]
Hi @Carlyx ,

![image](https://user-images.githubusercontent.com/19970321/198821986-30d3c0cd-51ed-4a33-b571-29149ab05d18.png)

I ran successfully on my side. That maybe caused by your environment. You can check if your installed ffmpeg is correct.

**Comment by Carlyx** [comment]
> Hi @Carlyx ,
> 
> ![image](https://user-images.githubusercontent.com/19970321/198821986-30d3c0cd-51ed-4a33-b571-29149ab05d18.png)
> 
> I ran successfully on my side. That may be caused by your environment. You can check whether your installed ffmpeg is correct.

Ok. Thanks for your help~  I will check it.   Again, awesome work!
