### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by WinnieLaugh** [harlanhong/CVPR2022-DaGAN#49]
Hi,

Thanks for this wonderful work!

It seems that the **_setup.py_** file is missing in this new version. Is it possible for you to upload it again? Thanks a lot for the help!

Best,
Wenhua

**Comment by harlanhong** [comment]
Hi @WinnieLaugh 

Could I know the error message you met? I cannot remember any setup.py file in my code :). Thanks.

**Comment by WinnieLaugh** [comment]
Sorry about that! I just found that the required 'setup.py' is for the  'face-alignment' lib. I was too blind to see the 'cd face-alignment' command.
