### ISSUE TITLE
 Add torch.device('cpu') when loading encoder/decoder weights for CPU use

### ISSUE THREAD

**Issue by tikitong** [harlanhong/CVPR2022-DaGAN#51]
In my case, inference with cpu via the `--cpu` argument needs the addition of `map_location=torch.device('cpu')` in `torch.load()` to succeed. Can you confirm? Many thanks!

https://github.com/harlanhong/CVPR2022-DaGAN/blob/78b22edcdbb4192b81c5adf343f980b42cddfe5d/demo.py#L166

```python
if opt.cpu:
  loaded_dict_enc = torch.load('checkpoints/depth_face_model/encoder.pth', map_location=torch.device('cpu'))
  loaded_dict_dec = torch.load('checkpoints/depth_face_model/depth.pth', map_location=torch.device('cpu'))
```

**Comment by harlanhong** [comment]
Correct. Thanks you.
