### ISSUE TITLE
real-time property of FDN

### ISSUE THREAD

**Issue by Bruce-yu199** [harlanhong/CVPR2022-DaGAN#55]
hi,
DaGAN is fantastic!
i'm  interested in the face depth network, and i want to know the real-time of FDN, or in other word, how much time it takes to infer a depth map of an input picture? because i want to know if it is suitable for mobile platform.

**Comment by harlanhong** [comment]
It can perform in real-time, at about 30 fps.

**Comment by Bruce-yu199** [comment]
> It can perform in real-time, at about 30 fps.

Thanks!
