### ISSUE TITLE
Do you provide Evaluation Metrics?

### ISSUE THREAD

**Issue by TropicalPenguinn** [harlanhong/CVPR2022-DaGAN#63]
Hello 

I find you have used SSIM,PSNR,AKD,AED,CSIM,PRMSE,AUCOn metrics but I can't see that in your codes. 

Could  you provide metrics codes that you have used for evaluation?

**Comment by harlanhong** [comment]
Thank you for your interest. While the specific metric implementations might not be included in our codebase, you can easily find many of them available online, as they are widely used in the field of image and video processing. Most of these metrics can be found in popular libraries like scikit-image.

However, we understand the importance of having a complete set of evaluation metrics for your project. I will work on releasing the specific implementations we used for our evaluation soon. Please stay tuned for updates regarding this.

In the meantime, feel free to explore the aforementioned libraries and online resources for implementations of these metrics. If you have any other questions or concerns, please don't hesitate to ask.

**Comment by TropicalPenguinn** [comment]
Thank you !!
